name: Deploy Java Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with Maven
        run: mvn clean package

      - name: Upload JAR file
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Download JAR file
        uses: actions/download-artifact@v3
        with:
          name: java-app
          path: target
          
      - name: Deploy JAR via SCP
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          HOSTNAME: ${{ secrets.SSH_IP}}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $HOSTNAME >> ~/.ssh/known_hosts
          scp -i ~/.ssh/id_rsa target/*.jar ubuntu@${{ secrets.SSH_IP }}:/home/ubuntu/
          
      - name: Copy JAR file to Deployment Directory
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          HOSTNAME: ${{ secrets.SSH_IP }}
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.SSH_IP }} 'sudo cp /home/ubuntu/*.jar /var/www/html/myjavaapp/'
          ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.SSH_HOST }} 'nohup java -jar /var/www/html/myjavaapp/*.jar > /var/www/html/myjavaapp/app.log 2>&1 &'
